 

// This file was automatically generated by the PetaPoco T4 Template
// Do not make changes directly to this file - edit the template instead
// 
// The following connection settings were used to generate this file
// 
//     Connection String Name: `WeiXin`
//     Provider:               `MySql.Data.MySqlClient`
//     Connection String:      `Server=localhost;Database='test';UID=root;Password=root`
//     Schema:                 `test`
//     Include Views:          `False`

//     Factory Name:          `MySqlClientFactory`
// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591

using System;

using ServiceStack.DataAnnotations;
using ServiceStack.Model;
using ServiceStack;

namespace sanfengli.Model.WeiXin
{
	[Alias("adminmenu")]
    public partial class adminmenu : IHasId<int> 
    {
        [Alias("Id")]
        [AutoIncrement]
        public int Id { get; set; }
        [Required]
		[Alias("PageName")]
        public string PageName { get; set; }
        [Required]
		[Alias("PageLink")]
        public string PageLink { get; set; }
        [Required]
		[Alias("ParentPage")]
        public int ParentPage { get; set; }
        [Required]
		[Alias("PageLive")]
        public int PageLive { get; set; }
        [Required]
		[Alias("Sort")]
        public int Sort { get; set; }
        [Required]
		[Alias("Editor")]
        public string Editor { get; set; }
        [Required]
		[Alias("CreateOn")]
        public DateTime CreateOn { get; set; }
    }

	[Alias("cyactivitycontent")]
    public partial class cyactivitycontent : IHasId<int> 
    {
        [Alias("Id")]
        [Required]
        public int Id { get; set; }
        [Required]
		[Alias("ActivityId")]
        public int ActivityId { get; set; }
        [Required]
		[Alias("ActivityNodes")]
        public string ActivityNodes { get; set; }
        [Required]
		[Alias("ActivityRandomVal")]
        public string ActivityRandomVal { get; set; }
        [Required]
		[Alias("CreateOn")]
        public DateTime CreateOn { get; set; }
        [Required]
		[Alias("UpdateOn")]
        public DateTime UpdateOn { get; set; }
    }

	[Alias("feedback")]
    public partial class feedback : IHasId<long> 
    {
        [Alias("Id")]
        [AutoIncrement]
        public long Id { get; set; }
        public int? UserId { get; set; }
        public string Content { get; set; }
        public string Image { get; set; }
        public DateTime? CreateOn { get; set; }
    }

	[Alias("mpeventreply")]
    public partial class mpeventreply : IHasId<int> 
    {
        [Alias("Id")]
        [AutoIncrement]
        public int Id { get; set; }
        [Required]
		[Alias("EventType")]
        public string EventType { get; set; }
        public string EventKey { get; set; }
        [Required]
		[Alias("ReplyType")]
        public string ReplyType { get; set; }
        public string ReplyContent { get; set; }
        [Required]
		[Alias("CreateOn")]
        public DateTime CreateOn { get; set; }
        [Required]
		[Alias("UpdateOn")]
        public DateTime UpdateOn { get; set; }
    }

	[Alias("mpmateriallib")]
    public partial class mpmateriallib : IHasId<int> 
    {
        [Alias("Id")]
        [AutoIncrement]
        public int Id { get; set; }
        [Required]
		[Alias("MType")]
        public string MType { get; set; }
        public string MediaId { get; set; }
        public string MName { get; set; }
        public string MUrl { get; set; }
        public string NewsContent { get; set; }
        public DateTime? UpdateTime { get; set; }
    }

	[Alias("mpmenulog")]
    public partial class mpmenulog : IHasId<int> 
    {
        [Alias("Id")]
        [AutoIncrement]
        public int Id { get; set; }
        public string Content { get; set; }
        public string Operator { get; set; }
        public DateTime? CreateOn { get; set; }
    }

	[Alias("mpmsgreply")]
    public partial class mpmsgreply : IHasId<int> 
    {
        [Alias("MsgId")]
        [Required]
        public int Id { get; set; }
        [Required]
		[Alias("RuleName")]
        public string RuleName { get; set; }
        public string ReplyMode { get; set; }
        public DateTime? CreateOn { get; set; }
        public DateTime? UpdateOn { get; set; }
    }

	[Alias("mpmsgreplycontent")]
    public partial class mpmsgreplycontent : IHasId<int> 
    {
        [Alias("ReplyId")]
        [Required]
        public int Id { get; set; }
        [Required]
		[Alias("MsgId")]
        public int MsgId { get; set; }
        public string ReplyType { get; set; }
        public string ReplyContent { get; set; }
        [Required]
		[Alias("CreateOn")]
        public DateTime CreateOn { get; set; }
        [Required]
		[Alias("UpdateOn")]
        public DateTime UpdateOn { get; set; }
    }

	[Alias("mpmsgreplykeys")]
    public partial class mpmsgreplykey : IHasId<int> 
    {
        [Alias("KeyId")]
        [Required]
        public int Id { get; set; }
        [Required]
		[Alias("MsgId")]
        public int MsgId { get; set; }
        public string KeyVal { get; set; }
        public string MatchMode { get; set; }
        [Required]
		[Alias("CreateOn")]
        public DateTime CreateOn { get; set; }
        [Required]
		[Alias("UpdateOn")]
        public DateTime UpdateOn { get; set; }
    }

	[Alias("wp_survey")]
    public partial class wp_survey : IHasId<uint> 
    {
        [Alias("id")]
        [AutoIncrement]
        public uint Id { get; set; }
        [Required]
		[Alias("keyword")]
        public string keyword { get; set; }
        public sbyte? keyword_type { get; set; }
        [Required]
		[Alias("title")]
        public string title { get; set; }
        public string intro { get; set; }
        public int? mTime { get; set; }
        public uint? cover { get; set; }
        public uint? cTime { get; set; }
        public string token { get; set; }
        public string finish_tip { get; set; }
        public string template { get; set; }
        public int? start_time { get; set; }
        public int? end_time { get; set; }
    }

	[Alias("wp_survey_answer")]
    public partial class wp_survey_answer : IHasId<uint> 
    {
        [Alias("id")]
        [AutoIncrement]
        public uint Id { get; set; }
        public uint? cTime { get; set; }
        public string token { get; set; }
        public uint? survey_id { get; set; }
        public uint? question_id { get; set; }
        public int? uid { get; set; }
        public string openid { get; set; }
        public string answer { get; set; }
    }

	[Alias("wp_survey_question")]
    public partial class wp_survey_question : IHasId<uint> 
    {
        [Alias("id")]
        [AutoIncrement]
        public uint Id { get; set; }
        [Required]
		[Alias("title")]
        public string title { get; set; }
        public string intro { get; set; }
        public uint? cTime { get; set; }
        public string token { get; set; }
        public uint? survey_id { get; set; }
        [Required]
		[Alias("type")]
        public string type { get; set; }
        public string extra { get; set; }
        public sbyte? is_must { get; set; }
        public uint? sort { get; set; }
    }

	[Alias("wp_user")]
    public partial class wp_user : IHasId<int> 
    {
        [Alias("uid")]
        [AutoIncrement]
        public int Id { get; set; }
        public string nickname { get; set; }
        public string password { get; set; }
        public string truename { get; set; }
        public string mobile { get; set; }
        public string email { get; set; }
        public sbyte? sex { get; set; }
        public string headimgurl { get; set; }
        public string city { get; set; }
        public string province { get; set; }
        public string country { get; set; }
        public string language { get; set; }
        public int? score { get; set; }
        public int? experience { get; set; }
        public string unionid { get; set; }
        public int? login_count { get; set; }
        public string reg_ip { get; set; }
        public int? reg_time { get; set; }
        public string last_login_ip { get; set; }
        public int? last_login_time { get; set; }
        public sbyte? status { get; set; }
        public sbyte? is_init { get; set; }
        public sbyte? is_audit { get; set; }
        public int? subscribe_time { get; set; }
        public string remark { get; set; }
        public int? groupid { get; set; }
        public sbyte? come_from { get; set; }
        public string login_password { get; set; }
        public int? manager_id { get; set; }
        public sbyte? level { get; set; }
        public string membership { get; set; }
    }

}
#pragma warning restore 1591
